# Generated by Django 2.2.16 on 2022-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_model_post_update'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique-follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique-follow'),
        ),
    ]
